language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-25.0.2
  - android-25
  - extra-google-m2repository
  - extra-android-m2repository
before_install:
- openssl aes-256-cbc -K $encrypted_cd6f32ab44b3_key -iv $encrypted_cd6f32ab44b3_iv
  -in voipms-sms/google-services.json.enc -out voipms-sms/google-services.json -d
